# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 09:54
from __future__ import unicode_literals

import dedupebackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueFile',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('mime_type', models.CharField(max_length=128, null=True)),
                ('size', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Unique, deduplicated file',
                'verbose_name_plural': 'Unique files',
            },
        ),
        migrations.AlterModelManagers(
            name='uniquefile',
            managers=[
                ('objects', dedupebackend.models.UniqueFileManager()),
            ],
        ),
    ]
